[msg MSG_002_0_0 [高巻 ¸]]
[s][bup 0 4 0 65535 0]Got new AP items. Test Value:[var 1][n][f 1 3 65535][w][e]

[msg MSG_NOTIFY_AP_LOCATION]
[s]Sent AP items![n][f 1 3 65535][w][e]

[msg MSG_CMM_52 [Sojiro]]
[s][bup 0 103 1 0 1]Unlocked [clr 12]Coffee Basics[clr 0]![n][w][e]

[msg MSG_CMM_55 [Sojiro]]
[s][bup 0 103 1 0 1]Unlocked [clr 12]LeBlanc Curry[clr 0]![n][w][e]

[msg MSG_CMM_4B [Ryuji]]
[s][bup 0 2 101 0 1]Unlocked [clr 12]Punk Talk[clr 0]![n][w][e]

[msg MSG_CMM_49 [Ryuji]]
[s][bup 0 2 101 0 1]Unlocked [clr 12]Follow Up[clr 0]![n][w][e]

[msg MSG_CMM_11B [Ryuji]]
[s][bup 0 2 101 0 1]Unlocked [clr 12]Stealth Dash[clr 0]![n][w][e]

[msg MSG_CMM_4A [Ryuji]]
[s][bup 0 2 101 0 1]Unlocked [clr 12]Harisen Recovery[clr 0]![n][w][e]

[msg MSG_CMM_50 [Ryuji]]
[s][bup 0 2 101 0 1]Unlocked [clr 12]Insta-kill[clr 0]![n][w][e]

[msg MSG_CMM_4D [Ryuji]]
[s][bup 0 2 101 0 1]Unlocked [clr 12]Endure[clr 0]![n][w][e]

[msg MSG_CMM_4F [Ryuji]]
[s][bup 0 2 101 0 1]Unlocked [clr 12]Protect[clr 0]![n][w][e]

[msg MSG_CMM_85 [Takemi]]
[s][bup 0 108 0 0 1]Unlocked [clr 12]Sterilization[clr 0]![n][w][e]

[msg MSG_CMM_89 [Takemi]]
[s][bup 0 108 0 0 1]Unlocked [clr 12]Immunization[clr 0]![n][w][e]

[msg MSG_CMM_87 [Takemi]]
[s][bup 0 108 0 0 1]Unlocked [clr 12]Discount[clr 0]![n][w][e]

[msg MSG_CMM_8B [Takemi]]
[s][bup 0 108 1 0 1]Unlocked [clr 12]Resuscitation[clr 0]![n][w][e]

[msg MSG_NOTIFY_INFILTRATION_LUST [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 0 3 0 0 0][f 4 10 65535 0 0][f 3 1 8 0 0 20 65535 0]We've got a route to [clr 10]Kamoshida's Palace[clr 0].[n][f 1 3 65535][f 1 1][e]
